#!/usr/bin/env python
# coding: utf-8

# In[1]:


from nse_scrap import *  


# In[2]:


# https://finlib.in/alphabets-in-the-stock-name/


# In[9]:


l = ['ABSLAMC','ADANIPORTS','ARE&M','AMBUJACEM','ASIANPAINT','ASPINWALL','AUROPHARMA','BAJAJ-AUTO','BAJFINANCE','BALKRISIND','CAMS','CARTRADE','CASTROLIND','CEATLTD','CIPLA','COALINDIA','CROMPTON','DATAPATTNS','DRREDDY','EIDPARRY','EMBASSY-RR','EXIDEIND','GAIL','GENUSPOWER','GESHIP','GOLDBEES','GOLDETF','GULFOILLUB','HCLTECH','HDFCBANK','HDFCNIFIT','HEROMOTOCO','HGS','HIL','HINDALCO','HITECHGEAR','ICICIBANK','ICICIGOLD','ICICITECH','IDFC','IFCI','INFY','IOC','IRBINVIT-IV','IRFC','ITC','JINDALPOLY','JINDALSAW','JSL','JUBLFOOD','KTKBANK','LGBBROSLTD','MANAPPURAM','MARUTI','MUTHOOTFIN','NATCOPHARM','NHIT-N1','NHIT-N3','NHIT-N2','PCBL','PETRONET','PGINVIT-IV','PNBGILTS','PPL','RUBFILA','RVNL','SAIL','SBIGETS','SGBN28VIII-GB','SIL-BE','STOVEKRAFT','TATACHEM','TATACOFFEE','TATAMOTORS','TATAMTRDVR','TATASTEEL','TCS','TECHM','TEGA','TITAGARH','TITAN','TMB','TTKPRESTIG','TVSMOTOR','VEDL','WHIRLPOOL','WIPRO','WSTCSTPAPR','ZYDUSLIFE']
# l = ['PGINVIT-IV', 'IRBINVIT-IV','RUBFILA','SIL-BE']
# Get_Stock_Data3(['ITC','INFY'], 250)
df = Get_Stock_Data3(l, 250, MAX_THREADS=10) 


# In[12]:


s1 = ['ABSLAMC','ADANIPORTS','ARE&M','AMBUJACEM','ASIANPAINT','ASPINWALL','AUROPHARMA','BAJAJ-AUTO','BAJFINANCE','BALKRISIND','CAMS','CARTRADE','CASTROLIND','CEATLTD','CIPLA','COALINDIA','CROMPTON','DATAPATTNS','DRREDDY','EIDPARRY','EMBASSY-RR','EXIDEIND','GAIL','GENUSPOWER','GESHIP','GOLDBEES','GOLDETF','GULFOILLUB','HCLTECH','HDFCBANK','HDFCNIFIT','HEROMOTOCO','HGS','HIL','HINDALCO','HITECHGEAR','ICICIBANK','ICICIGOLD','ICICITECH','IDFC','IFCI','INFY','IOC','IRBINVIT-IV','IRFC','ITC','JINDALPOLY','JINDALSAW','JSL','JUBLFOOD','KTKBANK','LGBBROSLTD','MANAPPURAM','MARUTI','MUTHOOTFIN','NATCOPHARM','NHIT-N1','NHIT-N3','NHIT-N2','PCBL','PETRONET','PGINVIT-IV','PNBGILTS','PPL','RUBFILA','RVNL','SAIL','SBIGETS','SGBN28VIII-GB','SIL-BE','STOVEKRAFT','TATACHEM','TATACOFFEE','TATAMOTORS','TATAMTRDVR','TATASTEEL','TCS','TECHM','TEGA','TITAGARH','TITAN','TMB','TTKPRESTIG','TVSMOTOR','VEDL','WHIRLPOOL','WIPRO','WSTCSTPAPR','ZYDUSLIFE']
SERIES_LIST = ['EQ', 'IV','N1','N2','N3','RR', 'GB','BE' ,'BZ', 'BL', 'ID', 'RR','RT','SM','ST', 'SO','GS','TB','MF','ME']
DEFAULT_SER = 'EQ'
ser = DEFAULT_SER
for name in s1:
    parts = name.split(sep="-")
    sname = parts[0]
    if(len(parts)>1): 
        ser = parts[1]
        if ser not in SERIES_LIST :
            ser = DEFAULT_SER
            sname=name
    else : ser = 'EQ'
    print(sname,":",ser)


# In[5]:


'EQ1' in ['EQ']


# In[1]:


import sys
import os
MY_PATH="C:/Users/111075866/Python Code/NSE/"
sys.path.append(MY_PATH)

from nse_scrap import *
import pandas as pd
import numpy as np
import yfinance as yf


# In[22]:


tkr = yf.Ticker('TCS.NSE')


# In[23]:


df  = pd.DataFrame.from_dict(tkr.info, orient='index').reset_index()


# In[ ]:


df.head(200)

